config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'reviews/index'
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/edit'

  resources :makeups do
    resources:reviews
 end
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/makeup.rb
class Makeup < ApplicationRecord
    has_many:reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :makeup
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/makeups_controller.rb
class MakeupsController < ApplicationController
  before_action :set_makeup, only: %i[ show edit update destroy ]

  # GET /makeups or /makeups.json
  def index
    @makeups = Makeup.all
  end

  # GET /makeups/1 or /makeups/1.json
  def show
  end

  # GET /makeups/new
  def new
    @makeup = Makeup.new
  end

  # GET /makeups/1/edit
  def edit
  end

  # POST /makeups or /makeups.json
  def create
    @makeup = Makeup.new(makeup_params)

    respond_to do |format|
      if @makeup.save
        format.html { redirect_to makeup_url(@makeup), notice: "Makeup was successfully created." }
        format.json { render :show, status: :created, location: @makeup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @makeup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makeups/1 or /makeups/1.json
  def update
    respond_to do |format|
      if @makeup.update(makeup_params)
        format.html { redirect_to makeup_url(@makeup), notice: "Makeup was successfully updated." }
        format.json { render :show, status: :ok, location: @makeup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @makeup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makeups/1 or /makeups/1.json
  def destroy
    @makeup.destroy

    respond_to do |format|
      format.html { redirect_to makeups_url, notice: "Makeup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_makeup
      @makeup = Makeup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def makeup_params
      params.require(:makeup).permit(:name, :rating, :colour)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @makeups = Makeups.find(params[:movie_id])
    @review = @makeups.review
  end

  def show
    @makeups = Makeups.find(params[:makeups_id])
    @review = @makeups.review.find(params[:id])   

  end

  def new
    @makeups = Makeups.find(params[makeups_id])
    @review = @makeups.review.build
  end

  def create
    @makeups = Makeups.find(params[makeups_id])
    @review = @makeups.review.build(params.require(:review).permit(:details))
    if @review.save
      redirect_to makeups_reviews_url(@makeups, @review)
    else
      render :action => "new"
    end
  end

  def edit
    @makeups = Makeups.find(params[:makeups_id])
    @review = @makeups.review.find(params[:id])
  end

  def update
    @makeups = Makeups.find(params[makeups_id])
    @review = Review.find(params[:id])
    if @review.update_attributes(params.require(:review).permit(:details))
      redirect_to makeups_reviews_url(@makeups, @review)
    else
      re :action => "edit"
    end
  end

  def destroy
    @makeups = Makeups.find(params[:makeups_id])
    @review = Review.find(params[:id])
    @review.destroy
    respond_to do |format|
      format.html {redirect_to makeups_reviews_path(@makeups) }
      format.xml {head :ok}
    end 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makeups_helper.rb
module MakeupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupAPP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div id="body">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/makeups/_form.html.erb
<%= form_with(model: makeup) do |form| %>
  <% if makeup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(makeup.errors.count, "error") %> prohibited this makeup from being saved:</h2>

      <ul>
        <% makeup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :colour, style: "display: block" %>
    <%= form.text_field :colour %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/makeups/_makeup.html.erb
<div id="<%= dom_id makeup %>">
  <p>
    <strong>Name:</strong>
    <%= makeup.name %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= makeup.rating %>
  </p>

  <p>
    <strong>Colour:</strong>
    <%= makeup.colour %>
  </p>

</div>

app/views/makeups/edit.html.erb
<h1>Editing makeup</h1>

<%= render "form", makeup: @makeup %>

<br>

<div>
  <%= link_to "Show this makeup", @makeup %> |
  <%= link_to "Back to makeups", makeups_path %>
</div>

app/views/makeups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Makeups</h1>

<div id="makeups">
  <% @makeups.each do |makeup| %>
    <%= render makeup %>
    <p>
      <%= link_to "Show this makeup", makeup %>
    </p>
  <% end %>
</div>

<%= link_to "New makeup", new_makeup_path %>

app/views/makeups/new.html.erb
<h1>New makeup</h1>

<%= render "form", makeup: @makeup %>

<br>

<div>
  <%= link_to "Back to makeups", makeups_path %>
</div>

app/views/makeups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @makeup %>

<div>
  <%= link_to "Edit this makeup", edit_makeup_path(@makeup) %> |
  <%= link_to "Back to makeups", makeups_path %>

  <%= button_to "Destroy this makeup", @makeup, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">John Smith</p>
        <p class="subtitle is-6">@johnsmith</p>
      </div>
    </div>

    <div class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Phasellus nec iaculis mauris. <a>@bulmaio</a>.
      <a href="#">#css</a> <a href="#">#responsive</a>
      <br>
      <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Reviews</h1>
<%= render 'form' %>
<%= link_to 'Show', makeups_review_path(@makeups, @review) %> |
<%= link_to 'Back', makeups_reviews_path(@makeups) %>


<%= form_for([@makeups, @review]) do |f| %>
    <% if @review.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error")%>
    prohibited this review from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    <div class="field">
    <p>
    <%= f.label :Details %><br />
    <%= f.text_field :details %>
    </p>
    </div>
    <div class="actions">
    <%= f.submit %>
    </div>
    <% end %>
    

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<table>
<tr>
<th>Review details</th>
<% for review in @reviews %>
<tr>
<td><%= review.details %></td>
<td><% link_to 'Show', makeups_review_path(@makeups, review) %></td>
<td><% link_to 'Edit', edit_movie_review_path(@makeups, review) %></td>
<td><%= link_to 'Destory', makeups_review_path(@makeups, review),
:confirm => 'Are you sure?', :method => :delete %></td>
</tr>
< % end %>
</table>
<br />
<%= link_to 'New review', new_movie_review_path(@makeups) %>
<%= link_to 'Back to Makeup', @makeups %>
 


<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>New Reviews</h1>
<%= render 'form' %>
<%= link_to 'Back', makeups_reviews_path(@makeups) %>

<%= form_for([@makeups, @review]) do |f| %>
    <% if @review.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error")%>
    prohibited this review from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    <div class="field">
    <p>
    <%= f.label :Details %><br />
    <%= f.text_field :details %>
    </p>
    </div>
    <div class="actions">
    <%= f.submit %>
    </div>
    <% end %>
    

app/views/reviews/show.html.erb
<h1>Review in <%= @makeups.title %></h1>
<p id="notice"><%= notice %></p>
<p>
<strong>Title:</strong>
<%= @movie.title %>
</p>
<p>
<strong>Rating:</strong>
<%= @makeups.rating %>
</p>
<p>
<strong>Release Date:</strong>
<%= @makeups.release %>
</p>
<!-- Display the reviews of a movie -->
<h2>Review</h2>
<% @makeups.review.each do |review| %>
    <p>
    <b>Review details:</b>
    <%= review.details %>
    </p>
    <% end %>

<%= link_to 'Edit', edit_makeups_review_path(@makeups, @review) %> |
<%= link_to 'Back', makeups_reviews_path(@makeups) %>
<%= link_to 'Show Reviews', makeups_review_path(@makeups) %>